### ISSUE TITLE
张子淳 技术岗笔试（mybot.js代码文件）

### ISSUE THREAD

**Issue by pollyxyx** [juzibot/Welcome#37]
期待你加入桔子互动！请将答案写在下面。

**Comment by windmemory** [comment]
能否描述一下这个机器人的功能是什么以及怎么使用？

**Comment by pollyxyx** [comment]
机器人人功能：将微信二维码打印到cmd命令行程序中，能够自动添加好友（备注含有关键词推荐）；识别发送的消息是否为群消息（将群名、发送人ID、消息打印在命令行窗口中）；暴露主机8888端口，在本地主机开启监听
使用：采用docker容器搭载wechaty镜像 在cmd命令行运行docker run -ti --name=mybot --rm --volume="$(pwd)":/bot -p 8888:8888 zixia/wechaty mybot.js（window将$(pwd)改为%cd%）

在 2019-05-05 18:14:35，"Yuan Gao" <notifications@github.com> 写道：


能否描述一下这个机器人的功能是什么以及怎么使用？

**Comment by genban** [comment]
## 项目运行

安装依赖
> cd {{项目路径}} && npm install

本地运行
> node mybot.js

执行成功
```
.....
Example app listening on port 8888!
Scan QR Code to login.....
```
## 功能描述

#### 启动一个Http Server开启监听端口8888
- [x] 设置解析JSON和UTF-8编码数据请求的最大数据量
- [x] 处理 http://localhost:8888 GET请求 响应"hello"

#### 启动微信机器人
- [x] 终端命令行扫二维码登陆
- [x] 新增好友处理
- [ ] 消息自动回复

```js
.on('Message', async (msg) => ..... 修改为 .on('message', async (msg) => ...
````

```js
Wechaty.instance().init() //  'init() DEPRECATED. use start() instead.
````
